# Generated by Django 2.2.10 on 2020-02-29 22:48

import courses.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200229_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='textbooks',
            field=djongo.models.fields.ArrayField(default=[], model_container=courses.models.Textbook),
            preserve_default=False,
        ),
    ]
