# Generated by Django 2.2.10 on 2020-02-29 22:52

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200229_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=[], primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
